<?php

namespace App\Services\Stats;

use App\Exceptions\StatsException;
use App\Models\Event;
use App\Models\EventRequest;
use App\Models\Payment;
use App\Models\User;
use App\Services\EventRequests\EventRequestEligibilityService;
use App\Services\RegistrationStatsService;
use App\Support\Money;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;

/**
 * Service providing a personalized dashboard and statistics for Clients.
 *
 * It aggregates data related to a client's own event requests and the revenue generated
 * by events organized on their behalf.
 */
class ClientStatsService
{
    /**
     * @param  RegistrationStatsService  $registrationStats  Service to handle registration counting.
     * @param  EventRequestEligibilityService  $eventRequestEligibility  Service to check if the client can submit new requests.
     */
    public function __construct(
        private readonly RegistrationStatsService $registrationStats,
        private readonly EventRequestEligibilityService $eventRequestEligibility,
    ) {}

    /**
     * Generates the statistical payload for a specific client.
     *
     * @param  User  $client  The client user instance.
     * @return array<string, mixed>
     *
     * @throws StatsException If the user is not a client.
     */
    public function payloadFor(User $client): array
    {
        $this->ensureClient($client);

        $email = (string) $client->getAttribute('email');
        $eventIds = $this->eventIdsFor($email);
        $requests = $this->requestsFor($email);
        $blockReason = $this->eventRequestEligibility->blockingReasonFor($client);

        return [
            'total_revenue' => $eventIds === [] ? 0.0 : $this->totalRevenue($eventIds),
            'featured_events' => $this->featuredEvents($email),
            'past_events' => $this->pastEvents($email),
            'can_submit_new_request' => $blockReason === null,
            'block_reason' => $blockReason,
            'requests' => $this->requestsByStatus($requests),
        ];
    }

    /**
     * Returns IDs of all events originating from this client's requests.
     *
     * @return list<string>
     */
    private function eventIdsFor(string $email): array
    {
        return Event::query()
            ->whereHas('eventRequest', fn ($query) => $query->where('contact_email', $email))
            ->pluck('id')
            ->map(fn (mixed $id): string => (string) $id)
            ->all();
    }

    /**
     * Fetches all event requests for a client email, including linked event data.
     *
     * @return EloquentCollection<int, EventRequest>
     */
    private function requestsFor(string $email): EloquentCollection
    {
        $requests = EventRequest::query()
            ->where('contact_email', $email)
            ->with([
                'event' => fn ($query) => $query->select('id', 'title', 'status', 'event_request_id', 'ticket_price_cents'),
            ])
            ->orderBy('created_at', 'desc')
            ->get();

        $events = $requests
            ->pluck('event')
            ->filter(fn (mixed $event): bool => $event instanceof Event)
            ->values();

        $this->registrationStats->attachCount($events, 'registrations_count');

        return $requests;
    }

    /**
     * Calculates total revenue generated by all events owned by this client.
     *
     * @param  list<string>  $eventIds
     */
    private function totalRevenue(array $eventIds): float
    {
        return Money::floatFromCents(Payment::query()
            ->whereHas('registration', fn ($query) => $query->whereIn('event_id', $eventIds))
            ->where('status', 'completed')
            ->sum('amount_cents'));
    }

    /**
     * Returns "Featured" (active/upcoming) events for the client.
     *
     * @return list<array<string, mixed>>
     */
    private function featuredEvents(string $email): array
    {
        $events = $this->clientEventsQuery($email)
            ->notFinished()
            ->orderBy('start_at', 'asc')
            ->get();

        $this->registrationStats->attachCount($events, 'tickets_count', 'paid');

        return $events->map(fn (Event $event): array => $this->formatEvent($event))->all();
    }

    /**
     * Returns past (finished) events for the client.
     *
     * @return list<array<string, mixed>>
     */
    private function pastEvents(string $email): array
    {
        $events = $this->clientEventsQuery($email)
            ->finished()
            ->orderBy('end_at', 'desc')
            ->orderBy('start_at', 'desc')
            ->get();

        $this->registrationStats->attachCount($events, 'tickets_count', 'paid');

        return $events->map(fn (Event $event): array => $this->formatEvent($event))->all();
    }

    /**
     * Scoped query for events linked to a client's approved requests.
     *
     * @return Builder<Event>
     */
    private function clientEventsQuery(string $email): Builder
    {
        return Event::query()
            ->where('status', Event::STATUS_PUBLISHED)
            ->whereHas('eventRequest', function ($query) use ($email): void {
                $query->where('contact_email', $email)
                    ->where('status', EventRequest::STATUS_APPROVED);
            })
            ->with(['organizer:id,name', 'eventRequest']);
    }

    /**
     * Formats an Event model for dashboard display.
     *
     * @return array<string, mixed>
     */
    private function formatEvent(Event $event): array
    {
        return [
            'id' => $event->getKey(),
            'title' => $event->getAttribute('title'),
            'description' => $event->getAttribute('description'),
            'image_url' => $event->getAttribute('image_url'),
            'location' => $event->getAttribute('location'),
            'start_at' => $event->getAttribute('start_at'),
            'end_at' => $event->getAttribute('end_at'),
            'registered_count' => $event->getAttribute('registered_count'),
            'capacity' => $event->getAttribute('capacity'),
            'tickets_count' => (int) $event->getAttribute('tickets_count'),
            'ticket_price' => (float) $event->getAttribute('ticket_price'),
            'organizer' => $event->relationLoaded('organizer') ? $event->getRelation('organizer') : null,
        ];
    }

    /**
     * Formats an EventRequest model, including registration metrics from its linked event.
     *
     * @return array<string, mixed>
     */
    private function formatRequest(EventRequest $request): array
    {
        $data = $request->toArray();
        $event = $request->relationLoaded('event') ? $request->getRelation('event') : null;
        $data['registrations_count'] = $event instanceof Event
            ? (int) $event->getAttribute('registrations_count')
            : 0;

        return $data;
    }

    /**
     * Groups event requests by their status (pending, approved, rejected).
     *
     * @param  EloquentCollection<int, EventRequest>  $requests
     * @return array<string, list<array<string, mixed>>>
     */
    private function requestsByStatus(EloquentCollection $requests): array
    {
        return [
            EventRequest::STATUS_PENDING => $this->formatRequestsWithStatus($requests, EventRequest::STATUS_PENDING),
            EventRequest::STATUS_APPROVED => $this->formatRequestsWithStatus($requests, EventRequest::STATUS_APPROVED),
            EventRequest::STATUS_REJECTED => $this->formatRequestsWithStatus($requests, EventRequest::STATUS_REJECTED),
        ];
    }

    /**
     * Filters and formats requests for a specific status.
     *
     * @param  EloquentCollection<int, EventRequest>  $requests
     * @return list<array<string, mixed>>
     */
    private function formatRequestsWithStatus(EloquentCollection $requests, string $status): array
    {
        return $requests
            ->where('status', $status)
            ->map(fn (EventRequest $request): array => $this->formatRequest($request))
            ->values()
            ->all();
    }

    /**
     * Enforces client-only access.
     *
     * @throws StatsException
     */
    private function ensureClient(User $user): void
    {
        if ($user->getAttribute('role') !== User::ROLE_CLIENT) {
            throw new StatsException('Accès refusé pour ce rôle.');
        }
    }
}
